export const REQUEST_LIST_USER = 'REQUEST_LIST_USER';
export const RECEIVE_LIST_USER = 'RECEIVE_LIST_USER';

export const REQUEST_GET_USER = 'REQUEST_GET_USER';
export const RECEIVE_GET_USER = 'RECEIVE_GET_USER';

export const REQUEST_UPDATE_USER = 'REQUEST_USER_UPDATE';
export const RECEIVE_UPDATE_USER = 'RECEIVE_USER_UPDATE';

export const REQUEST_DELETE_USER = 'REQUEST_DELETE_USER';
export const RECEIVE_DELETE_USER = 'RECEIVE_DELETE_USER';

const USER_URL = 'http://localhost:10080/';